spring:
  datasource:
#    url: jdbc:h2:tcp://localhost/~/jpashop
#    url: jdbc:h2:mem://localhost/~/jpashop
    url: jdbc:mariadb://rds-mariadb.c346c7pkd3yp.ap-northeast-2.rds.amazonaws.com:3306/jpashop
#   username: sa
#   password:
    username: namiezexx
    password: jslee0707!
#    driver-class-name: org.h2.Driver
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect  # JPA MariaDB 데이터베이스 플랫폼을 지정
    hibernate:
      #ddl-auto: create
      ddl-auto: none
    properties:
      hibernate:
#        show_sql: true
        format_sql: true

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace  #jpa 쿼리의 파라미터를 로그로 남긴다.
    